Repository halo-sigs/plugin-migrate, pull requests merged in 2022-12, with the labels that each got.

#5 docs: refine readme
  README.md
Labels: kind/documentation, lgtm, approved, release-note-none

#6 feat: add import data API for migration
  src/main/java/run/halo/migrate/MigrationController.java
  src/main/resources/extensions/roleTemplate.yaml
Labels: lgtm, approved, release-note

#8 refactor: use import api to get migration data
  console/src/views/MigrateView.vue
  src/main/resources/console/main.js
Labels: lgtm, approved, release-note-none, kind/improvement

#7 feat: add import post and sheet metas support
  console/src/composables/use-migrate-from-halo.ts
  console/src/types/models.ts
  console/src/views/MigrateView.vue
  src/main/resources/console/main.js
Labels: kind/feature, lgtm, approved, release-note-none
