Repository halo-sigs/plugin-migrate, pull requests merged in 2023-08, with the labels that each got.

#25 fix: add s3os object key
  console/src/composables/use-migrate-from-halo.ts
Labels: kind/bug, lgtm, approved, release-note

#26 Refactor import strategy to support multiple providers
  .gitignore
  build.gradle
  console/package.json
  console/pnpm-lock.yaml
  console/src/assets/atom.svg
  console/src/assets/rss.svg
  console/src/assets/wordpress.svg
  console/src/components/AttachmentPolicy.vue
  console/src/components/FileSelector.vue
  console/src/components/MigratePreview.vue
  console/src/components/MigratePreviewItem.vue
  console/src/components/MigrateProvider.vue
  console/src/components/StepButton.vue
  console/src/components/Steps.vue
  console/src/composables/use-migrate-from-halo.ts
  console/src/composables/use-migrate-task.ts
  console/src/modules/atom/AtomMigrateDataParser.vue
  console/src/modules/atom/use-atom-data-parser.ts
  console/src/modules/halo/HaloMigrateDataParser.vue
  console/src/modules/halo/use-halo-data-parser.ts
  console/src/modules/index.ts
  console/src/modules/rss/RssMigrateDataParser.vue
  console/src/modules/rss/use-rss-data-parser.ts
  console/src/modules/wordpress/WordPressMigrateDataParser.vue
  console/src/modules/wordpress/use-wordpress-data-parser.ts
  console/src/types/index.ts
  console/src/types/models.ts
  console/src/utils/id.ts
  console/src/views/MigrateView.vue
  console/tsconfig.app.json
  console/tsconfig.config.json
  console/tsconfig.vitest.json
  console/vite.config.ts
  docs/.vitepress/config.ts
  docs/extend/provider.md
  docs/extend/steps.md
  docs/img/halo-provider-data-export.png
  docs/img/halo-provider-migrate-plugin.png
  docs/index.md
  docs/package.json
  docs/pnpm-lock.yaml
  docs/provider/atom.md
  docs/provider/halo.md
  docs/provider/rss.md
  docs/provider/wordpress.md
  docs/public/halo-favicon.webp
  docs/public/halo-logo.png
  src/main/java/run/halo/migrate/DataBufferUtils.java
  src/main/java/run/halo/migrate/MigrationController.java
  src/main/resources/console/main.js
  src/main/resources/console/style.css
  src/main/resources/extensions/roleTemplate.yaml
Labels: kind/feature, lgtm, approved, release-note, kind/improvement

#27 chore: update project infrastructure and docs
  .github/workflows/workflow.yaml
  README.md
  build.gradle
  console/package.json
  console/pnpm-lock.yaml
  docs/provider/halo.md
  settings.gradle
  src/main/resources/console/main.js
  src/main/resources/console/style.css
Labels: lgtm, approved, release-note, kind/improvement
