Repository halo-sigs/plugin-migrate, pull requests merged in 2023-04, with the labels that each got.

#18 chore: update plugin gradle
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  lib/halo-2.0.0-SNAPSHOT-plain.jar
  src/main/java/run/halo/migrate/DataBufferUtils.java
  src/main/java/run/halo/migrate/MigratePlugin.java
  src/main/java/run/halo/migrate/MigrationController.java
  src/main/resources/console/main.js
  src/main/resources/plugin.yaml
Labels: lgtm, approved, release-note-none, kind/improvement

#19 feat: add migration supports for journals, photos and links.
  console/package.json
  console/pnpm-lock.yaml
  console/src/composables/use-migrate-from-halo.ts
  console/src/types/models.ts
  console/src/views/MigrateView.vue
  console/vite.config.ts
  src/main/resources/console/main.js
Labels: kind/feature, lgtm, approved, release-note

#21 feat: add migration supports for attachment
  console/src/composables/use-migrate-from-halo.ts
  console/src/types/models.ts
  console/src/views/MigrateView.vue
  src/main/resources/console/main.js
  src/main/resources/console/style.css
Labels: kind/feature, lgtm, approved, release-note

#22 chore: release 1.2.0
  gradle.properties
  src/main/resources/plugin.yaml
Labels: lgtm, approved, release-note-none
