Repository halo-sigs/plugin-migrate, pull requests merged in 2024-06, with the labels that each got.

#42 chore: add app-id annotation
  src/main/resources/plugin.yaml
Labels: lgtm, approved, release-note-none

#43 chore: update project infra
  .github/workflows/cd.yaml
  .github/workflows/ci.yaml
  .github/workflows/workflow.yaml
  build.gradle
  console/package.json
  console/pnpm-lock.yaml
  console/src/index.ts
  console/src/views/MigrateView.vue
  console/vite.config.ts
  src/main/resources/logo.png
  src/main/resources/logo.svg
  src/main/resources/plugin.yaml
Labels: release-note, kind/improvement

#46 refactor: remove role template
  console/env.d.ts
  console/src/index.ts
  src/main/resources/extensions/roleTemplate.yaml
Labels: lgtm, approved, release-note

#49 feat: support data migration for Ghost platform
  README.md
  build.gradle
  console/.eslintrc.cjs
  console/src/assets/ghost.png
  console/src/modules/ghost/GhostMigrateDataParser.vue
  console/src/modules/ghost/types.ts
  console/src/modules/ghost/use-ghost-data-parser.ts
  console/src/modules/index.ts
  docs/.vitepress/config.mts
  docs/img/ghost-1.png
  docs/img/ghost-2.png
  docs/img/ghost-3.png
  docs/img/ghost-4.png
  docs/index.md
  docs/package.json
  docs/pnpm-lock.yaml
  docs/provider/ghost.md
  docs/public/halo-favicon.webp
  docs/public/halo-logo.png
  docs/public/logo.svg
Labels: kind/feature, lgtm, approved, release-note

#47 refactor: auto-generate excerpt if it's empty
  console/src/modules/wordpress/use-wordpress-data-parser.ts
Labels: kind/feature, lgtm, approved, release-note

#48 fix: resolve issue with post slug possibly being empty during wordpress importing
  console/src/modules/wordpress/use-wordpress-data-parser.ts
Labels: kind/bug, lgtm, approved, release-note

#50 feat: optimize layout styling
  console/package.json
  console/pnpm-lock.yaml
  console/postcss.config.cjs
  console/prettier.config.cjs
  console/prettier.config.js
  console/src/components/AttachmentPolicy.vue
  console/src/components/FileSelector.vue
  console/src/components/MigrateProvider.vue
  console/src/composables/use-migrate-task.ts
  console/src/modules/atom/use-atom-data-parser.ts
  console/src/modules/halo/use-halo-data-parser.ts
  console/src/modules/hugo/HugoMigrateDataParser.vue
  console/src/modules/hugo/hugo-data-parser.ts
  console/src/modules/hugo/markdown-it-id.ts
  console/src/modules/index.ts
  console/src/modules/rss/use-rss-data-parser.ts
  console/src/modules/wordpress/use-wordpress-data-parser.ts
  console/src/utils/api-client.ts
  console/src/views/MigrateView.vue
  console/tailwind.config.cjs
Labels: approved, release-note

#51 docs: update readme
  README.md
  docs/img/screenshot.png
  docs/index.md
Labels: kind/documentation, lgtm, approved, release-note-none
