Repository halo-sigs/plugin-migrate, pull requests merged in 2024-07, with the labels that each got.

#53 chore: remove deprecated plugin wrapper
  src/main/java/run/halo/migrate/MigratePlugin.java
Labels: lgtm, approved, release-note-none

#52 refactor: use globally provided axios instance
  build.gradle
  console/package.json
  console/pnpm-lock.yaml
  console/src/components/AttachmentPolicy.vue
  console/src/composables/use-migrate-task.ts
  console/src/utils/api-client.ts
  console/src/views/MigrateView.vue
  src/main/resources/plugin.yaml
Labels: lgtm, approved, release-note, kind/improvement

#54 fix: resolve issue where WordPress import fails with a single tag
  console/src/modules/wordpress/use-wordpress-data-parser.ts
Labels: kind/bug, lgtm, release-note
